# ============================================================
# AD34 2023 Chartbook — PDF Compilation
# ============================================================

rm(list = ls())
library(tidyverse)
library(reportlab) # nope — not in R
# Use R's native PDF system instead
library(grid)
library(png)
library(gridExtra)

setwd("~/Mayoral Results AD34/outputs/AD34_outputs")

# ------------------------------------------------------------
# 1) Helper to embed a PNG in the PDF (full page)
# ------------------------------------------------------------
add_image_page <- function(filename, title = NULL) {
  img <- tryCatch(readPNG(filename), error = function(e) NULL)
  if (is.null(img)) return()
  grid.newpage()
  pushViewport(viewport(layout = grid.layout(2, 1,
                                             heights = unit(c(0.9, 9.1), "null"))))
  if (!is.null(title)) {
    grid.text(title, vp = viewport(layout.pos.row = 1),
              gp = gpar(fontsize = 16, fontface = "bold"))
  }
  grid.raster(img, width = unit(1, "npc"), height = unit(1, "npc"),
              vp = viewport(layout.pos.row = 2))
}

# ------------------------------------------------------------
# 2) Open the PDF
# ------------------------------------------------------------
pdf("AD34_Chartbook_2023.pdf", width = 8.5, height = 11)

# --- Cover Page ---
grid.newpage()
grid.text("Queens Assembly District 34 — ACS 2023 Chartbook",
          y = 0.7, gp = gpar(fontsize = 20, fontface = "bold"))
grid.text("Poverty • Foreign-Born • Transit • Ancestry",
          y = 0.63, gp = gpar(fontsize = 14))
grid.text("Data Source: 2019–2023 American Community Survey (5-year)",
          y = 0.55, gp = gpar(fontsize = 10, fontface = "italic"))
grid.text(Sys.Date(), y = 0.48, gp = gpar(fontsize = 9))
grid.text("Generated by R (tidycensus, ggplot2, viridis, patchwork)",
          y = 0.43, gp = gpar(fontsize = 8, col = "gray40"))
grid.text("Author: William Kay", y = 0.37, gp = gpar(fontsize = 10))

# ------------------------------------------------------------
# 3) Insert Maps & Charts (only if they exist)
# ------------------------------------------------------------
# poverty + foreign-born maps
if (file.exists("map_poverty.png")) add_image_page("map_poverty.png", "Poverty by Census Tract (AD34)")
if (file.exists("map_foreign.png")) add_image_page("map_foreign.png", "Foreign-Born Population (AD34)")

# transit maps and bars
if (file.exists("map_bus_all.png")) add_image_page("map_bus_all.png", "Bus Commute (% of All Workers)")
if (file.exists("bar_bus_all.png")) add_image_page("bar_bus_all.png", "Bus Commute — AD34 vs NYC")
if (file.exists("bar_subway_all.png")) add_image_page("bar_subway_all.png", "Subway Commute — AD34 vs NYC")
if (file.exists("bar_bus_of_pt.png")) add_image_page("bar_bus_of_pt.png", "Bus Share of Public Transit Users — AD34 vs NYC")

# socio-economic bars
if (file.exists("bar_poverty.png")) add_image_page("bar_poverty.png", "Poverty Rates — AD34 vs NYC")
if (file.exists("bar_foreign.png")) add_image_page("bar_foreign.png", "Foreign-Born Share — AD34 vs NYC")

# ancestry map last
if (file.exists("map_ancestry.png")) add_image_page("map_ancestry.png", "Most Common Ancestry by Tract")

# ------------------------------------------------------------
# 4) Close PDF
# ------------------------------------------------------------
dev.off()
message("💾 Saved: AD34_Chartbook_2023.pdf")
